---
# destination type could be "s3" or "node"
# - "node" only available for "Node Monitoring Agent" >= v1.6.1
destinationType: node

# target node(s), the node name should match the NAME from `kubectl get nodes`
# $ kubectl get nodes -o jsonpath='{range .items[*]}{"- "}{.metadata.name}{"\n"}{end}'
nodes:
- ip-192-168-100-200.ec2.internal
- i-EXAMPLE1111111111
